ini_open("kit.ini")
a = ini_read_real("init", "licence", 0)
b = ini_read_real("init", "arg", 0)
c = ini_read_real("init", "api", 0)
d = ini_read_real("init", "sd", 0)
e = ini_read_real("init", "git", 0)
f = ini_read_real("init", "se1d", 0)
g = ini_read_real("init", "id", 0)
h = ini_read_real("init", "sus", 0)
i = ini_read_real("init", "cat", 0)
j = ini_read_real("init", "kernel", 0)
k = ini_read_real("init", "fish", 0)
l = ini_read_real("init", "wtf", 0)
m = ini_read_real("init", "sigma", 0)
n = ini_read_real("init", "rizz", 0)
o = ini_read_real("init", "imei", 0)
p = ini_read_real("init", "gd&p", 0)
q = ini_read_real("init", "vnc", 0)
r = ini_read_real("init", "CBO", 0)
s = ini_read_real("init", "beta", 0)
t = ini_read_real("init", "soon", 0)
u = ini_read_real("init", "def", 0)
v = ini_read_real("init", "windows11isbetterthanwindows10acceptthis", 0)
w = ini_read_real("init", "obj", 0)
z = ini_read_real("init", "trashcan", 0)
ini_close()