draw_set_font(fnt25)
draw_self()
draw_text(x + 50, y + 50, "You won!")
draw_text(x + 50, y + 100, global.lvname)
draw_text(x + 50, y + 150, global.lvauth)
draw_healthbar(x + 50, y + 200, x + 654, y + 232, global.scorew_perc, c_black, c_white, c_white, 0, true, true)
draw_text(x + 50, y + 282, string(global.scorew) + " of " + string(global.scorew_max))